// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using geoTagNinja;
//
//    var gtnReleasesApiResponse = GtnReleasesApiResponse.FromJson(jsonString);

namespace GeoTagNinja
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text.Json.Serialization;

    public partial class GTNReleaseAPIResponse
    {
        // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
        public class Asset
        {
            [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
            public string url { get; set; }

            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public int id { get; set; }

            [JsonProperty("node_id", NullValueHandling = NullValueHandling.Ignore)]
            public string node_id { get; set; }

            [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
            public string name { get; set; }

            [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
            public object label { get; set; }

            [JsonProperty("uploader", NullValueHandling = NullValueHandling.Ignore)]
            public Uploader uploader { get; set; }

            [JsonProperty("content_type", NullValueHandling = NullValueHandling.Ignore)]
            public string content_type { get; set; }

            [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
            public string state { get; set; }

            [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
            public int size { get; set; }

            [JsonProperty("digest", NullValueHandling = NullValueHandling.Ignore)]
            public string digest { get; set; }

            [JsonProperty("download_count", NullValueHandling = NullValueHandling.Ignore)]
            public int download_count { get; set; }

            [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime created_at { get; set; }

            [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime updated_at { get; set; }

            [JsonProperty("browser_download_url", NullValueHandling = NullValueHandling.Ignore)]
            public string browser_download_url { get; set; }
        }

        public class Author
        {
            [JsonProperty("login", NullValueHandling = NullValueHandling.Ignore)]
            public string login { get; set; }

            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public int id { get; set; }

            [JsonProperty("node_id", NullValueHandling = NullValueHandling.Ignore)]
            public string node_id { get; set; }

            [JsonProperty("avatar_url", NullValueHandling = NullValueHandling.Ignore)]
            public string avatar_url { get; set; }

            [JsonProperty("gravatar_id", NullValueHandling = NullValueHandling.Ignore)]
            public string gravatar_id { get; set; }

            [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
            public string url { get; set; }

            [JsonProperty("html_url", NullValueHandling = NullValueHandling.Ignore)]
            public string html_url { get; set; }

            [JsonProperty("followers_url", NullValueHandling = NullValueHandling.Ignore)]
            public string followers_url { get; set; }

            [JsonProperty("following_url", NullValueHandling = NullValueHandling.Ignore)]
            public string following_url { get; set; }

            [JsonProperty("gists_url", NullValueHandling = NullValueHandling.Ignore)]
            public string gists_url { get; set; }

            [JsonProperty("starred_url", NullValueHandling = NullValueHandling.Ignore)]
            public string starred_url { get; set; }

            [JsonProperty("subscriptions_url", NullValueHandling = NullValueHandling.Ignore)]
            public string subscriptions_url { get; set; }

            [JsonProperty("organizations_url", NullValueHandling = NullValueHandling.Ignore)]
            public string organizations_url { get; set; }

            [JsonProperty("repos_url", NullValueHandling = NullValueHandling.Ignore)]
            public string repos_url { get; set; }

            [JsonProperty("events_url", NullValueHandling = NullValueHandling.Ignore)]
            public string events_url { get; set; }

            [JsonProperty("received_events_url", NullValueHandling = NullValueHandling.Ignore)]
            public string received_events_url { get; set; }

            [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
            public string type { get; set; }

            [JsonProperty("user_view_type", NullValueHandling = NullValueHandling.Ignore)]
            public string user_view_type { get; set; }

            [JsonProperty("site_admin", NullValueHandling = NullValueHandling.Ignore)]
            public bool site_admin { get; set; }
        }

        public class Root
        {
            [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
            public string url { get; set; }

            [JsonProperty("assets_url", NullValueHandling = NullValueHandling.Ignore)]
            public string assets_url { get; set; }

            [JsonProperty("upload_url", NullValueHandling = NullValueHandling.Ignore)]
            public string upload_url { get; set; }

            [JsonProperty("html_url", NullValueHandling = NullValueHandling.Ignore)]
            public string html_url { get; set; }

            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public int id { get; set; }

            [JsonProperty("author", NullValueHandling = NullValueHandling.Ignore)]
            public Author author { get; set; }

            [JsonProperty("node_id", NullValueHandling = NullValueHandling.Ignore)]
            public string node_id { get; set; }

            [JsonProperty("tag_name", NullValueHandling = NullValueHandling.Ignore)]
            public string tag_name { get; set; }

            [JsonProperty("target_commitish", NullValueHandling = NullValueHandling.Ignore)]
            public string target_commitish { get; set; }

            [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
            public string name { get; set; }

            [JsonProperty("draft", NullValueHandling = NullValueHandling.Ignore)]
            public bool draft { get; set; }

            [JsonProperty("immutable", NullValueHandling = NullValueHandling.Ignore)]
            public bool immutable { get; set; }

            [JsonProperty("prerelease", NullValueHandling = NullValueHandling.Ignore)]
            public bool prerelease { get; set; }

            [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime created_at { get; set; }

            [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime updated_at { get; set; }

            [JsonProperty("published_at", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime published_at { get; set; }

            [JsonProperty("assets", NullValueHandling = NullValueHandling.Ignore)]
            public List<Asset> assets { get; set; }

            [JsonProperty("tarball_url", NullValueHandling = NullValueHandling.Ignore)]
            public string tarball_url { get; set; }

            [JsonProperty("zipball_url", NullValueHandling = NullValueHandling.Ignore)]
            public string zipball_url { get; set; }

            [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
            public string body { get; set; }
        }

        public class Uploader
        {
            [JsonProperty("login", NullValueHandling = NullValueHandling.Ignore)]
            public string login { get; set; }

            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public int id { get; set; }

            [JsonProperty("node_id", NullValueHandling = NullValueHandling.Ignore)]
            public string node_id { get; set; }

            [JsonProperty("avatar_url", NullValueHandling = NullValueHandling.Ignore)]
            public string avatar_url { get; set; }

            [JsonProperty("gravatar_id", NullValueHandling = NullValueHandling.Ignore)]
            public string gravatar_id { get; set; }

            [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
            public string url { get; set; }

            [JsonProperty("html_url", NullValueHandling = NullValueHandling.Ignore)]
            public string html_url { get; set; }

            [JsonProperty("followers_url", NullValueHandling = NullValueHandling.Ignore)]
            public string followers_url { get; set; }

            [JsonProperty("following_url", NullValueHandling = NullValueHandling.Ignore)]
            public string following_url { get; set; }

            [JsonProperty("gists_url", NullValueHandling = NullValueHandling.Ignore)]
            public string gists_url { get; set; }

            [JsonProperty("starred_url", NullValueHandling = NullValueHandling.Ignore)]
            public string starred_url { get; set; }

            [JsonProperty("subscriptions_url", NullValueHandling = NullValueHandling.Ignore)]
            public string subscriptions_url { get; set; }

            [JsonProperty("organizations_url", NullValueHandling = NullValueHandling.Ignore)]
            public string organizations_url { get; set; }

            [JsonProperty("repos_url", NullValueHandling = NullValueHandling.Ignore)]
            public string repos_url { get; set; }

            [JsonProperty("events_url", NullValueHandling = NullValueHandling.Ignore)]
            public string events_url { get; set; }

            [JsonProperty("received_events_url", NullValueHandling = NullValueHandling.Ignore)]
            public string received_events_url { get; set; }

            [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
            public string type { get; set; }

            [JsonProperty("user_view_type", NullValueHandling = NullValueHandling.Ignore)]
            public string user_view_type { get; set; }

            [JsonProperty("site_admin", NullValueHandling = NullValueHandling.Ignore)]
            public bool site_admin { get; set; }
        }

    }

    public partial class GTNReleaseAPIResponse
    {
        public static GTNReleaseAPIResponse[] FromJson(string json) => JsonConvert.DeserializeObject<GTNReleaseAPIResponse[]>(json, GeoTagNinja.Converter.Settings);
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this GtnReleasesApiResponse[] self) => JsonConvert.SerializeObject(self, geoTagNinja.Converter.Settings);
    //}
    //
    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
