using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Windows.Forms;

namespace GeoTagNinja;

/// <summary>
///     This is generated by a template so I'm not adding extra commentary. Atm it's pretty basic anyway
///     ... it just pulls some of the Assembly info. If someone is genuienly courious, open an issue.
/// </summary>
internal partial class FrmAboutBox : Form
{
    public FrmAboutBox()
    {
        InitializeComponent();
        Text = string.Format(format: "About {0}", arg0: AssemblyTitle);
        lbl_ProductName.Text = AssemblyProduct;
        lbl_Version.Text = string.Format(format: "Version {0}", arg0: Assembly.GetExecutingAssembly()
                                                                          .GetName()
                                                                          .Version.Major +
                                                                      "." +
                                                                      Assembly.GetExecutingAssembly()
                                                                          .GetName()
                                                                          .Version.Minor +
                                                                      "." +
                                                                      Assembly.GetExecutingAssembly()
                                                                          .GetName()
                                                                          .Version.Build.ToString(provider: CultureInfo.InvariantCulture));
        lbl_Copyright.Text = AssemblyCopyright;
        lbl_CompanyName.Text = AssemblyCompany;
        tbx_Description.Text = AssemblyDescription;
        lbl_Paypal.Links.Clear();
        lbl_Paypal.Links.Add(start: 0, length: lbl_Paypal.Width, linkData: "https://www.paypal.com/donate/?hosted_button_id=R5GSBXW8A5NNN");
    }

    private void Btn_OK_Click(object sender,
                              EventArgs e)
    {
        Hide();
    }

    private void lbl_Paypal_Click(object sender,
                                  EventArgs e)
    {
        Process.Start(fileName: "https://www.paypal.com/donate/?hosted_button_id=R5GSBXW8A5NNN");
    }

    private void lbl_website_LinkClicked(object sender,
                                         LinkLabelLinkClickedEventArgs e)
    {
        Process.Start(fileName: e.Link.LinkData as string);
    }

    private void FrmAboutBox_Load(object sender,
                                  EventArgs e)
    {
        LinkLabel.Link link = new();
        link.LinkData = "https://geotag.ninja";
        lbl_website.Links.Add(value: link);
    }

    #region Assembly Attribute Accessors

    public string AssemblyTitle
    {
        get
        {
            object[] attributes = Assembly.GetExecutingAssembly()
                .GetCustomAttributes(attributeType: typeof(AssemblyTitleAttribute), inherit: false);
            if (attributes.Length > 0)
            {
                AssemblyTitleAttribute titleAttribute = (AssemblyTitleAttribute)attributes[0];
                if (titleAttribute.Title != "")
                {
                    return titleAttribute.Title;
                }
            }

            return Path.GetFileNameWithoutExtension(path: Assembly.GetExecutingAssembly()
                                                        .CodeBase);
        }
    }

    public string AssemblyVersion => Assembly.GetExecutingAssembly()
        .GetName()
        .Version.ToString();

    public string AssemblyDescription
    {
        get
        {
            object[] attributes = Assembly.GetExecutingAssembly()
                .GetCustomAttributes(attributeType: typeof(AssemblyDescriptionAttribute), inherit: false);
            if (attributes.Length == 0)
            {
                return "";
            }

            return ((AssemblyDescriptionAttribute)attributes[0]).Description;
        }
    }

    public string AssemblyProduct
    {
        get
        {
            object[] attributes = Assembly.GetExecutingAssembly()
                .GetCustomAttributes(attributeType: typeof(AssemblyProductAttribute), inherit: false);
            if (attributes.Length == 0)
            {
                return "";
            }

            return ((AssemblyProductAttribute)attributes[0]).Product;
        }
    }

    public string AssemblyCopyright
    {
        get
        {
            object[] attributes = Assembly.GetExecutingAssembly()
                .GetCustomAttributes(attributeType: typeof(AssemblyCopyrightAttribute), inherit: false);
            if (attributes.Length == 0)
            {
                return "";
            }

            return ((AssemblyCopyrightAttribute)attributes[0]).Copyright;
        }
    }

    public string AssemblyCompany
    {
        get
        {
            object[] attributes = Assembly.GetExecutingAssembly()
                .GetCustomAttributes(attributeType: typeof(AssemblyCompanyAttribute), inherit: false);
            if (attributes.Length == 0)
            {
                return "";
            }

            return ((AssemblyCompanyAttribute)attributes[0]).Company;
        }
    }

    #endregion
}