// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GeoTagNinja;
//
//    var geoResponse = GeoResponse.FromJson(JsonString);

namespace geoTagNinja
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    public partial class GeoResponseToponomy
    {
        [JsonProperty("geonames", NullValueHandling = NullValueHandling.Ignore)]
        public Geoname[] Geonames { get; set; }
    }
    public partial class GeoResponseToponomy
    {
        public static GeoResponseToponomy FromJson(string Json) => JsonConvert.DeserializeObject<GeoResponseToponomy>(Json, geoTagNinja.Converter.Settings);
    }
    public partial class Geoname
    {
        [JsonProperty("adminCode1", NullValueHandling = NullValueHandling.Ignore)]
        public string AdminCode1 { get; set; }

        [JsonProperty("lng", NullValueHandling = NullValueHandling.Ignore)]
        public string Lng { get; set; }

        [JsonProperty("distance", NullValueHandling = NullValueHandling.Ignore)]
        public string Distance { get; set; }

        [JsonProperty("geonameId", NullValueHandling = NullValueHandling.Ignore)]
        public long? GeonameId { get; set; }

        [JsonProperty("toponymName", NullValueHandling = NullValueHandling.Ignore)]
        public string ToponymName { get; set; }

        [JsonProperty("countryId", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? CountryId { get; set; }

        [JsonProperty("fcl", NullValueHandling = NullValueHandling.Ignore)]
        public string Fcl { get; set; }

        [JsonProperty("population", NullValueHandling = NullValueHandling.Ignore)]
        public long? Population { get; set; }

        [JsonProperty("countryCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryCode { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("fclName", NullValueHandling = NullValueHandling.Ignore)]
        public string FclName { get; set; }

        [JsonProperty("adminCodes1", NullValueHandling = NullValueHandling.Ignore)]
        public AdminCodes1 AdminCodes1 { get; set; }

        [JsonProperty("countryName", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryName { get; set; }

        [JsonProperty("fcodeName", NullValueHandling = NullValueHandling.Ignore)]
        public string FcodeName { get; set; }

        [JsonProperty("adminName1", NullValueHandling = NullValueHandling.Ignore)]
        public string AdminName1 { get; set; }
        [JsonProperty("adminName2", NullValueHandling = NullValueHandling.Ignore)]
        public string AdminName2 { get; set; }

        [JsonProperty("lat", NullValueHandling = NullValueHandling.Ignore)]
        public string Lat { get; set; }

        [JsonProperty("fcode", NullValueHandling = NullValueHandling.Ignore)]
        public string Fcode { get; set; }
    }
    public partial class AdminCodes1
    {
        [JsonProperty("ISO3166_2", NullValueHandling = NullValueHandling.Ignore)]
        public string Iso31662 { get; set; }
    }
    public partial class GeoResponseAltitude
    {
        [JsonProperty("srtm1", NullValueHandling = NullValueHandling.Ignore)]
        public long? Srtm1 { get; set; }

        [JsonProperty("lng", NullValueHandling = NullValueHandling.Ignore)]
        public double? Lng { get; set; }

        [JsonProperty("lat", NullValueHandling = NullValueHandling.Ignore)]
        public double? Lat { get; set; }
    }
    public partial class GeoResponseAltitude
    {
        public static GeoResponseAltitude FromJson(string Json) => JsonConvert.DeserializeObject<GeoResponseAltitude>(Json, geoTagNinja.Converter.Settings);
    }
    public static class Serialize
    {
        public static string ToJson(this GeoResponseToponomy self) => JsonConvert.SerializeObject(self, geoTagNinja.Converter.Settings);
    }
    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
