//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Button {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Button() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.Button", typeof(Button).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Move to Next.
        /// </summary>
        public static string btn_ApplyAndNext {
            get {
                return ResourceManager.GetString("btn_ApplyAndNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TakenDate.
        /// </summary>
        public static string btn_InsertFromTakenDate {
            get {
                return ResourceManager.GetString("btn_InsertFromTakenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the &quot;latest&quot; Paste Settings.
        /// </summary>
        public static string btn_PullMostRecentPasteSettings {
            get {
                return ResourceManager.GetString("btn_PullMostRecentPasteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the &quot;latest&quot; Shift Settings.
        /// </summary>
        public static string btn_PullMostRecentTrackSyncShift {
            get {
                return ResourceManager.GetString("btn_PullMostRecentTrackSyncShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove GPS and Location data.
        /// </summary>
        public static string btn_RemoveGeoData {
            get {
                return ResourceManager.GetString("btn_RemoveGeoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string btn_ResetToDefaults {
            get {
                return ResourceManager.GetString("btn_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Later.
        /// </summary>
        public static string btn_RestartLater {
            get {
                return ResourceManager.GetString("btn_RestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Now.
        /// </summary>
        public static string btn_RestartNow {
            get {
                return ResourceManager.GetString("btn_RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current values for all images selected for editing....
        /// </summary>
        public static string btn_SetCurrentValues {
            get {
                return ResourceManager.GetString("btn_SetCurrentValues", resourceCulture);
            }
        }
    }
}
