//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColumnHeader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColumnHeader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.ColumnHeader", typeof(ColumnHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank out?.
        /// </summary>
        public static string clh_BlankOutTargetPoint {
            get {
                return ResourceManager.GetString("clh_BlankOutTargetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        public static string clh_DataPointConditionType {
            get {
                return ResourceManager.GetString("clh_DataPointConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string clh_DataPointConditionValue {
            get {
                return ResourceManager.GetString("clh_DataPointConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        public static string clh_DataPointName {
            get {
                return ResourceManager.GetString("clh_DataPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exif (GTN Internal) Tag.
        /// </summary>
        public static string clh_ExifTag {
            get {
                return ResourceManager.GetString("clh_ExifTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified (Unsaved) Value.
        /// </summary>
        public static string clh_ModifiedValue {
            get {
                return ResourceManager.GetString("clh_ModifiedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original (Saved) Value.
        /// </summary>
        public static string clh_OriginalValue {
            get {
                return ResourceManager.GetString("clh_OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string clh_TargetPointName {
            get {
                return ResourceManager.GetString("clh_TargetPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads city from.
        /// </summary>
        public static string clh_TargetPointNameCustomCityLogic {
            get {
                return ResourceManager.GetString("clh_TargetPointNameCustomCityLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becomes.
        /// </summary>
        public static string clh_TargetPointOutcome {
            get {
                return ResourceManager.GetString("clh_TargetPointOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Outcome.
        /// </summary>
        public static string clh_TargetPointOutcomeCustom {
            get {
                return ResourceManager.GetString("clh_TargetPointOutcomeCustom", resourceCulture);
            }
        }
    }
}
