//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.Form", typeof(Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string FrmEditFileData {
            get {
                return ResourceManager.GetString("FrmEditFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import GPX/JSON Data.
        /// </summary>
        public static string FrmImportExportGpx {
            get {
                return ResourceManager.GetString("FrmImportExportGpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favourites.
        /// </summary>
        public static string FrmManageFavourites {
            get {
                return ResourceManager.GetString("FrmManageFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste…What?.
        /// </summary>
        public static string FrmPasteWhat {
            get {
                return ResourceManager.GetString("FrmPasteWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Toponymy Values.
        /// </summary>
        public static string FrmPickDataFromAPIBox {
            get {
                return ResourceManager.GetString("FrmPickDataFromAPIBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the folder loads..
        /// </summary>
        public static string FrmPleaseWaitBox {
            get {
                return ResourceManager.GetString("FrmPleaseWaitBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FrmSettings {
            get {
                return ResourceManager.GetString("FrmSettings", resourceCulture);
            }
        }
    }
}
