//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generic_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generic_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.Generic_Strings", typeof(Generic_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Generic_All {
            get {
                return ResourceManager.GetString("Generic_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Generic_City {
            get {
                return ResourceManager.GetString("Generic_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Generic_Coordinates {
            get {
                return ResourceManager.GetString("Generic_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Generic_Country {
            get {
                return ResourceManager.GetString("Generic_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string Generic_CountryCode {
            get {
                return ResourceManager.GetString("Generic_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string Generic_CreateDate {
            get {
                return ResourceManager.GetString("Generic_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Generic_Days {
            get {
                return ResourceManager.GetString("Generic_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string Generic_Decimal {
            get {
                return ResourceManager.GetString("Generic_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Generic_Delete {
            get {
                return ResourceManager.GetString("Generic_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Coordinates.
        /// </summary>
        public static string Generic_DestCoordinates {
            get {
                return ResourceManager.GetString("Generic_DestCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Generic_Export {
            get {
                return ResourceManager.GetString("Generic_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp Value.
        /// </summary>
        public static string Generic_ExportTrackTimeStampType {
            get {
                return ResourceManager.GetString("Generic_ExportTrackTimeStampType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Time.
        /// </summary>
        public static string Generic_ExposureTime {
            get {
                return ResourceManager.GetString("Generic_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Generic_Favourites {
            get {
                return ResourceManager.GetString("Generic_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Generic_Feet {
            get {
                return ResourceManager.GetString("Generic_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string Generic_Feet_Abbr {
            get {
                return ResourceManager.GetString("Generic_Feet_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Date.
        /// </summary>
        public static string Generic_FileModifyDate {
            get {
                return ResourceManager.GetString("Generic_FileModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string Generic_FileName {
            get {
                return ResourceManager.GetString("Generic_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string Generic_Fnumber {
            get {
                return ResourceManager.GetString("Generic_Fnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal Length.
        /// </summary>
        public static string Generic_FocalLength {
            get {
                return ResourceManager.GetString("Generic_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal Length (35mm).
        /// </summary>
        public static string Generic_FocalLengthIn35mmFormat {
            get {
                return ResourceManager.GetString("Generic_FocalLengthIn35mmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For All Images.
        /// </summary>
        public static string Generic_ForAllImages {
            get {
                return ResourceManager.GetString("Generic_ForAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For This Image.
        /// </summary>
        public static string Generic_ForThisImage {
            get {
                return ResourceManager.GetString("Generic_ForThisImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Generic_GPSAltitude {
            get {
                return ResourceManager.GetString("Generic_GPSAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Ref.
        /// </summary>
        public static string Generic_GPSAltitudeRef {
            get {
                return ResourceManager.GetString("Generic_GPSAltitudeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS DateTime.
        /// </summary>
        public static string Generic_GPSDateTime {
            get {
                return ResourceManager.GetString("Generic_GPSDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Latitude.
        /// </summary>
        public static string Generic_GPSDestLatitude {
            get {
                return ResourceManager.GetString("Generic_GPSDestLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Latitude Ref.
        /// </summary>
        public static string Generic_GPSDestLatitudeRef {
            get {
                return ResourceManager.GetString("Generic_GPSDestLatitudeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Longitude.
        /// </summary>
        public static string Generic_GPSDestLongitude {
            get {
                return ResourceManager.GetString("Generic_GPSDestLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Longitude Ref.
        /// </summary>
        public static string Generic_GPSDestLongitudeRef {
            get {
                return ResourceManager.GetString("Generic_GPSDestLongitudeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img Direction.
        /// </summary>
        public static string Generic_GPSImgDirection {
            get {
                return ResourceManager.GetString("Generic_GPSImgDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img Direction Ref.
        /// </summary>
        public static string Generic_GPSImgDirectionRef {
            get {
                return ResourceManager.GetString("Generic_GPSImgDirectionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Generic_GPSLatitude {
            get {
                return ResourceManager.GetString("Generic_GPSLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude Ref.
        /// </summary>
        public static string Generic_GPSLatitudeRef {
            get {
                return ResourceManager.GetString("Generic_GPSLatitudeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Generic_GPSLongitude {
            get {
                return ResourceManager.GetString("Generic_GPSLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude Ref.
        /// </summary>
        public static string Generic_GPSLongitudeRef {
            get {
                return ResourceManager.GetString("Generic_GPSLongitudeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Generic_GPSSpeed {
            get {
                return ResourceManager.GetString("Generic_GPSSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Ref.
        /// </summary>
        public static string Generic_GPSSpeedRef {
            get {
                return ResourceManager.GetString("Generic_GPSSpeedRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string Generic_GUID {
            get {
                return ResourceManager.GetString("Generic_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Generic_Hours {
            get {
                return ResourceManager.GetString("Generic_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Generic_Import {
            get {
                return ResourceManager.GetString("Generic_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Generic_Insert {
            get {
                return ResourceManager.GetString("Generic_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPTC Keywords.
        /// </summary>
        public static string Generic_IPTCKeywords {
            get {
                return ResourceManager.GetString("Generic_IPTCKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Speed.
        /// </summary>
        public static string Generic_ISO {
            get {
                return ResourceManager.GetString("Generic_ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens.
        /// </summary>
        public static string Generic_LensSpec {
            get {
                return ResourceManager.GetString("Generic_LensSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Generic_Make {
            get {
                return ResourceManager.GetString("Generic_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres.
        /// </summary>
        public static string Generic_Metres {
            get {
                return ResourceManager.GetString("Generic_Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Generic_Metres_Abbr {
            get {
                return ResourceManager.GetString("Generic_Metres_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Generic_Miles {
            get {
                return ResourceManager.GetString("Generic_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Generic_Minutes {
            get {
                return ResourceManager.GetString("Generic_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Generic_Model {
            get {
                return ResourceManager.GetString("Generic_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Generic_None {
            get {
                return ResourceManager.GetString("Generic_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone Offset.
        /// </summary>
        public static string Generic_OffsetTime {
            get {
                return ResourceManager.GetString("Generic_OffsetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls wait....
        /// </summary>
        public static string Generic_PleaseWait {
            get {
                return ResourceManager.GetString("Generic_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Ask again.
        /// </summary>
        public static string Generic_QuestionDontAskAgain {
            get {
                return ResourceManager.GetString("Generic_QuestionDontAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Generic_Rating {
            get {
                return ResourceManager.GetString("Generic_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Generic_Rename {
            get {
                return ResourceManager.GetString("Generic_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Current Changes.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secs.
        /// </summary>
        public static string Generic_Seconds {
            get {
                return ResourceManager.GetString("Generic_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string Generic_State {
            get {
                return ResourceManager.GetString("Generic_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublocation.
        /// </summary>
        public static string Generic_Sublocation {
            get {
                return ResourceManager.GetString("Generic_Sublocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Date.
        /// </summary>
        public static string Generic_TakenDate {
            get {
                return ResourceManager.GetString("Generic_TakenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone Adjustment:.
        /// </summary>
        public static string Generic_TZTime {
            get {
                return ResourceManager.GetString("Generic_TZTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DST?.
        /// </summary>
        public static string Generic_UseDST {
            get {
                return ResourceManager.GetString("Generic_UseDST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Subjects.
        /// </summary>
        public static string Generic_XMLSubjects {
            get {
                return ResourceManager.GetString("Generic_XMLSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
    }
}
