//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.GroupBox", typeof(GroupBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string gbx_AppSettings {
            get {
                return ResourceManager.GetString("gbx_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string gbx_CreateDate {
            get {
                return ResourceManager.GetString("gbx_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string gbx_Dates {
            get {
                return ResourceManager.GetString("gbx_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images selected for editing.
        /// </summary>
        public static string gbx_EditImageList {
            get {
                return ResourceManager.GetString("gbx_EditImageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoNames Language Settings.
        /// </summary>
        public static string gbx_GeoNamesLanguageSettings {
            get {
                return ResourceManager.GetString("gbx_GeoNamesLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoNames Settings.
        /// </summary>
        public static string gbx_GeoNamesSettings {
            get {
                return ResourceManager.GetString("gbx_GeoNamesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Altitude data.
        /// </summary>
        public static string gbx_GetAltitude {
            get {
                return ResourceManager.GetString("gbx_GetAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Toponomy data.
        /// </summary>
        public static string gbx_GetToponomy {
            get {
                return ResourceManager.GetString("gbx_GetToponomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Data.
        /// </summary>
        public static string gbx_GPSData {
            get {
                return ResourceManager.GetString("gbx_GPSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string gbx_ImportExportGpxSource {
            get {
                return ResourceManager.GetString("gbx_ImportExportGpxSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Setting.
        /// </summary>
        public static string gbx_ImportExportGpxTimeSetting {
            get {
                return ResourceManager.GetString("gbx_ImportExportGpxTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Data.
        /// </summary>
        public static string gbx_LocationData {
            get {
                return ResourceManager.GetString("gbx_LocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Colour Mode.
        /// </summary>
        public static string gbx_MapColourMode {
            get {
                return ResourceManager.GetString("gbx_MapColourMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string gbx_OtherSettings {
            get {
                return ResourceManager.GetString("gbx_OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Track (Options).
        /// </summary>
        public static string gbx_SaveTrackTo {
            get {
                return ResourceManager.GetString("gbx_SaveTrackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Image) Taken.
        /// </summary>
        public static string gbx_TakenDate {
            get {
                return ResourceManager.GetString("gbx_TakenDate", resourceCulture);
            }
        }
    }
}
