//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.MessageBox", typeof(MessageBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing folder to DirectoryElements.
        /// </summary>
        public static string mbx_DirectoryElementCollection_ErrorParsing {
            get {
                return ResourceManager.GetString("mbx_DirectoryElementCollection_ErrorParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app encountered errors communicating with the API. If you got an Unauthorised error, pls set your username as password in the settings..
        /// </summary>
        public static string mbx_FrmEditFileData_ErrorAPIError {
            get {
                return ResourceManager.GetString("mbx_FrmEditFileData_ErrorAPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be a bug.  Please file an issue on github and that the &apos;sender&apos; was: .
        /// </summary>
        public static string mbx_FrmEditFileData_ErrorInvalidSender {
            get {
                return ResourceManager.GetString("mbx_FrmEditFileData_ErrorInvalidSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated..
        /// </summary>
        public static string mbx_FrmEditFileData_InfoDataUpdated {
            get {
                return ResourceManager.GetString("mbx_FrmEditFileData_InfoDataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your files seem to have disappeared..
        /// </summary>
        public static string mbx_FrmEditFileData_WarningFileDisappeared {
            get {
                return ResourceManager.GetString("mbx_FrmEditFileData_WarningFileDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This needs to have numbers only. Will default to zero..
        /// </summary>
        public static string mbx_FrmEditFileData_WarningLatLongMustBeNumbers {
            get {
                return ResourceManager.GetString("mbx_FrmEditFileData_WarningLatLongMustBeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to see the report on the import process?.
        /// </summary>
        public static string mbx_FrmImportExportGpx_AskUserWantsReport {
            get {
                return ResourceManager.GetString("mbx_FrmImportExportGpx_AskUserWantsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or folder you picked is invalid..
        /// </summary>
        public static string mbx_FrmImportExportGpx_FileOrFolderDoesntExist {
            get {
                return ResourceManager.GetString("mbx_FrmImportExportGpx_FileOrFolderDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been selected to import for..
        /// </summary>
        public static string mbx_FrmImportExportGpx_NoFileSelected {
            get {
                return ResourceManager.GetString("mbx_FrmImportExportGpx_NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import Track overlay - found no relevant-looking data..
        /// </summary>
        public static string mbx_FrmImportExportGpx_TrackContainsNoData {
            get {
                return ResourceManager.GetString("mbx_FrmImportExportGpx_TrackContainsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;shift&quot; values stored. Data will remain 0..
        /// </summary>
        public static string mbx_FrmImportNoStoredShiftValues {
            get {
                return ResourceManager.GetString("mbx_FrmImportNoStoredShiftValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create SQLite database (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorCantCreateSQLiteDB {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorCantCreateSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from SQL Failed (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorCantLoadSQLiteDB {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorCantLoadSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading webview2 - Have you installed it?.
        /// </summary>
        public static string mbx_FrmMainApp_ErrorCantLoadWebView2 {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorCantLoadWebView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read default values from SQL (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorCantReadDefaultSQLiteDB {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorCantReadDefaultSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created but can&apos;t write SQLite database (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorCantWriteSQLiteDB {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorCantWriteSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing the filedata-Q tables (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorClearingFileDataQTables {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorClearingFileDataQTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleBuffer Error (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorDoubleBuffer {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorDoubleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no longer appears to exist: .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorFileGoneMissing {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorFileGoneMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitializeComponent (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeComponent {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (await wbv_MapArea.EnsureCoreWebView2Async(c2wv)) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewEnsureCoreWebView2Async {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewEnsureCoreWebView2Async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (IsWebMessageEnabled) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewIsWebMessageEnabled {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewIsWebMessageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (NavigateToString in HTMLCode file) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewNavigateToStringInHTMLFile {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewNavigateToStringInHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (parsing coordinates from HTMLCode file) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewParseCoordsFromHTMLFile {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewParseCoordsFromHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (reading HTMLCode file) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewReadHTMLFile {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewReadHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.InitialiseWebView (replacing constants in HTMLCode file) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewReplaceStringInHTMLFile {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewReplaceStringInHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while performing  wbv_MapArea_WebMessageReceived (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInitializeWebViewWebMessageReceived {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInitializeWebViewWebMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you entered doesn&apos;t seem valid. Revert to C:\?.
        /// </summary>
        public static string mbx_FrmMainApp_ErrorInvalidFolder {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorInvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the language file and assigning columnheaders (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorLanguageFileColumnHeaders {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorLanguageFileColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in FrmMainApp.NavigateMapGo (string HTMLCode) (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorNavigateMapGoHTMLCode {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorNavigateMapGoHTMLCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing Columns failed (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorResizingColumns {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorResizingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Default Startup folder failed (Please file an issue on github): .
        /// </summary>
        public static string mbx_FrmMainApp_ErrorSettingStartupFolder {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_ErrorSettingStartupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been removed. Either you didn&apos;t select valid items or the ones you picked didn&apos;t have cached data..
        /// </summary>
        public static string mbx_FrmMainApp_InfoCahcedDataNotRemoved {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_InfoCahcedDataNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there was any, cached data for selected items has been removed..
        /// </summary>
        public static string mbx_FrmMainApp_InfoCahcedDataRemoved {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_InfoCahcedDataRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty/blank.
        /// </summary>
        public static string mbx_FrmMainApp_InfoFavouriteNameCannotBeBlank {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_InfoFavouriteNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saved item you selected isn&apos;t valid.
        /// </summary>
        public static string mbx_FrmMainApp_InfoFavouriteNotValid {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_InfoFavouriteNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite saved OK.
        /// </summary>
        public static string mbx_FrmMainApp_InfoFavouriteSaved {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_InfoFavouriteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no favourites defined. Add one using the buttons under the map..
        /// </summary>
        public static string mbx_FrmMainApp_NoFavouritesDefined {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_NoFavouritesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to assign the coordinates to the selected file(s)?.
        /// </summary>
        public static string mbx_FrmMainApp_QuestionAddDraggedDataPointToFiles {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_QuestionAddDraggedDataPointToFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API query didn&apos;t return any valid information. Do you want to blank out the toponomy values?.
        /// </summary>
        public static string mbx_FrmMainApp_QuestionNoRowsFromAPI {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_QuestionNoRowsFromAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the following sidecar files share names with multiple image files - data may have been misread:.
        /// </summary>
        public static string mbx_FrmMainApp_WarningMultipleImageFilesForXMP {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_WarningMultipleImageFilesForXMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item selected..
        /// </summary>
        public static string mbx_FrmMainApp_WarningNoItemSelected {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_WarningNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisely 1 file must be selected..
        /// </summary>
        public static string mbx_FrmMainApp_WarningTooManyFilesSelected {
            get {
                return ResourceManager.GetString("mbx_FrmMainApp_WarningTooManyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values specified in the Copy Pool for DateTime Shift.
        /// </summary>
        public static string mbx_FrmPasteWhat_NoDateShiftToPaste {
            get {
                return ResourceManager.GetString("mbx_FrmPasteWhat_NoDateShiftToPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dropdown columns must have a non-empty value and also the &quot;if&quot; condition value must not be empty..
        /// </summary>
        public static string mbx_FrmSettings_dgv_CustomRules_ColumnCannotBeEmpty {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_dgv_CustomRules_ColumnCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you pick &quot;Custom&quot; for Outcome then the Custom Outcome column must not be empty. If you close the Settings Form and this isn&apos;t fixed, your row will be deleted..
        /// </summary>
        public static string mbx_FrmSettings_dgv_CustomRules_CustomOutcomeCannotBeEmpty {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_dgv_CustomRules_CustomOutcomeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Failed: .
        /// </summary>
        public static string mbx_FrmSettings_ErrorExportFailed {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_ErrorExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Failed: .
        /// </summary>
        public static string mbx_FrmSettings_ErrorImportFailed {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_ErrorImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app for the change to take place..
        /// </summary>
        public static string mbx_FrmSettings_PleaseRestartApp {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_PleaseRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to Export. Please note that the Export function exports data that is _in_ the database, or in other words has been saved. If you have pending changes in Settings then back out, save them (click OK in the Settings Form), then come back here..
        /// </summary>
        public static string mbx_FrmSettings_QuestionWhatToExport {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_QuestionWhatToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to Import. Please note that upon successful completion of the Import process the relevant bits of the database will be overwritten. If something fails there will be a backup file of your db in your AppData folder..
        /// </summary>
        public static string mbx_FrmSettings_QuestionWhatToImport {
            get {
                return ResourceManager.GetString("mbx_FrmSettings_QuestionWhatToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string mbx_GenericDone {
            get {
                return ResourceManager.GetString("mbx_GenericDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done - you will probably want to restart the app..
        /// </summary>
        public static string mbx_GenericDoneRestartApp {
            get {
                return ResourceManager.GetString("mbx_GenericDoneRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path likely contains UTF (non-standard, such as Asian, Cyrillic, etc.) characters and this may cause the error. Please make sure you have enabled the “Use Unicode UTF-8 for worldwide language support” feature. (refer to the Known Issues in the Readme for this).
        /// </summary>
        public static string mbx_GenericPathLikelyUTF {
            get {
                return ResourceManager.GetString("mbx_GenericPathLikelyUTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asyncExifTool.ExecuteAsync failed (Please file an issue on github): .
        /// </summary>
        public static string mbx_Helper_ErrorAsyncExifToolExecuteAsyncFailed {
            get {
                return ResourceManager.GetString("mbx_Helper_ErrorAsyncExifToolExecuteAsyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read default values from SQL (Please file an issue on github): .
        /// </summary>
        public static string mbx_Helper_ErrorCantReadDefaultSQLiteDB {
            get {
                return ResourceManager.GetString("mbx_Helper_ErrorCantReadDefaultSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data has been changed - want to save? 
        ///Data will be discarded if you click No.
        /// </summary>
        public static string mbx_Helper_QuestionFileQIsNotEmpty {
            get {
                return ResourceManager.GetString("mbx_Helper_QuestionFileQIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExifToolVerAPIResponse API Returned the following response: .
        /// </summary>
        public static string mbx_Helper_WarningExifToolVerAPIResponse {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningExifToolVerAPIResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your files seem to have disappeared..
        /// </summary>
        public static string mbx_Helper_WarningFileDisappeared {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningFileDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoNames API Returned the following response: .
        /// </summary>
        public static string mbx_Helper_WarningGeoNamesAPIResponse {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningGeoNamesAPIResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub API Returned the following response: .
        /// </summary>
        public static string mbx_Helper_WarningGTNVerAPIResponse {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningGTNVerAPIResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need to provide an ArcGIS API Key in the Settings for the app to work properly..
        /// </summary>
        public static string mbx_Helper_WarningNoARCGISKey {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningNoARCGISKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing in your write-queue..
        /// </summary>
        public static string mbx_Helper_WarningNothingInWriteQueue {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningNothingInWriteQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Paste..
        /// </summary>
        public static string mbx_Helper_WarningNothingToPaste {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningNothingToPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve disabled both processing of the original file _and_ the sidecar XMP so there is nothing to write to..
        /// </summary>
        public static string mbx_Helper_WarningNoWriteSettingEnabled {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningNoWriteSettingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will only work if you have one and only one file selected..
        /// </summary>
        public static string mbx_Helper_WarningTooManyFilesSelected {
            get {
                return ResourceManager.GetString("mbx_Helper_WarningTooManyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reach the API - are you offline by any chance?.
        /// </summary>
        public static string mbx_HelperStaticExifNoAPI {
            get {
                return ResourceManager.GetString("mbx_HelperStaticExifNoAPI", resourceCulture);
            }
        }
    }
}
