//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadioButton {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadioButton() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.RadioButton", typeof(RadioButton).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Fixed Date.
        /// </summary>
        public static string rbt_CreateDateSetToFixedDate {
            get {
                return ResourceManager.GetString("rbt_CreateDateSetToFixedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Shift.
        /// </summary>
        public static string rbt_CreateDateTimeShift {
            get {
                return ResourceManager.GetString("rbt_CreateDateTimeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from another folder.
        /// </summary>
        public static string rbt_importFromAnotherFolder {
            get {
                return ResourceManager.GetString("rbt_importFromAnotherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from the current folder.
        /// </summary>
        public static string rbt_importFromCurrentFolder {
            get {
                return ResourceManager.GetString("rbt_importFromCurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from a chosen file.
        /// </summary>
        public static string rbt_importOneFile {
            get {
                return ResourceManager.GetString("rbt_importOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark (Inverse).
        /// </summary>
        public static string rbt_MapColourModeDarkInverse {
            get {
                return ResourceManager.GetString("rbt_MapColourModeDarkInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark (Pale).
        /// </summary>
        public static string rbt_MapColourModeDarkPale {
            get {
                return ResourceManager.GetString("rbt_MapColourModeDarkPale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string rbt_MapColourModeNormal {
            get {
                return ResourceManager.GetString("rbt_MapColourModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual (Fixed values).
        /// </summary>
        public static string rbt_PasteCreateDateActual {
            get {
                return ResourceManager.GetString("rbt_PasteCreateDateActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Shift.
        /// </summary>
        public static string rbt_PasteCreateDateShift {
            get {
                return ResourceManager.GetString("rbt_PasteCreateDateShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual (Fixed values).
        /// </summary>
        public static string rbt_PasteTakenDateActual {
            get {
                return ResourceManager.GetString("rbt_PasteTakenDateActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Shift.
        /// </summary>
        public static string rbt_PasteTakenDateShift {
            get {
                return ResourceManager.GetString("rbt_PasteTakenDateShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Fixed Date.
        /// </summary>
        public static string rbt_TakenDateSetToFixedDate {
            get {
                return ResourceManager.GetString("rbt_TakenDateSetToFixedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Shift.
        /// </summary>
        public static string rbt_TakenDateTimeShift {
            get {
                return ResourceManager.GetString("rbt_TakenDateTimeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to use this language when retrieving location names:.
        /// </summary>
        public static string rbt_TryUseGeoNamesLanguage {
            get {
                return ResourceManager.GetString("rbt_TryUseGeoNamesLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to use the &quot;local language&quot; when retrieving location names.
        /// </summary>
        public static string rbt_UseGeoNamesLocalLanguage {
            get {
                return ResourceManager.GetString("rbt_UseGeoNamesLocalLanguage", resourceCulture);
            }
        }
    }
}
