//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.TabPage", typeof(TabPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string tpg_Application {
            get {
                return ResourceManager.GetString("tpg_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom City Assignment Logic.
        /// </summary>
        public static string tpg_CustomCityLogic {
            get {
                return ResourceManager.GetString("tpg_CustomCityLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rules.
        /// </summary>
        public static string tpg_CustomRules {
            get {
                return ResourceManager.GetString("tpg_CustomRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string tpg_DateTime {
            get {
                return ResourceManager.GetString("tpg_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exif.
        /// </summary>
        public static string tpg_Exif {
            get {
                return ResourceManager.GetString("tpg_Exif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Options.
        /// </summary>
        public static string tpg_FileOptions {
            get {
                return ResourceManager.GetString("tpg_FileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoNames Settings.
        /// </summary>
        public static string tpg_GeoNames {
            get {
                return ResourceManager.GetString("tpg_GeoNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tracks.
        /// </summary>
        public static string tpg_ImportExport_Export {
            get {
                return ResourceManager.GetString("tpg_ImportExport_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tracks.
        /// </summary>
        public static string tpg_ImportExport_Import {
            get {
                return ResourceManager.GetString("tpg_ImportExport_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string tpg_Location {
            get {
                return ResourceManager.GetString("tpg_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string tpg_Map {
            get {
                return ResourceManager.GetString("tpg_Map", resourceCulture);
            }
        }
    }
}
