//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTagNinja.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolStripMenuItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolStripMenuItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTagNinja.Resources.Languages.ToolStripMenuItem", typeof(ToolStripMenuItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Coordinates in API.
        /// </summary>
        public static string cmi_OpenCoordsInAPI {
            get {
                return ResourceManager.GetString("cmi_OpenCoordsInAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cached Data.
        /// </summary>
        public static string cmi_removeCachedData {
            get {
                return ResourceManager.GetString("cmi_removeCachedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or Hide Columns.
        /// </summary>
        public static string cmi_ShowHideCols {
            get {
                return ResourceManager.GetString("cmi_ShowHideCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string tmi_File {
            get {
                return ResourceManager.GetString("tmi_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All Geodata.
        /// </summary>
        public static string tmi_File_CopyGeoData {
            get {
                return ResourceManager.GetString("tmi_File_CopyGeoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Files.
        /// </summary>
        public static string tmi_File_EditFiles {
            get {
                return ResourceManager.GetString("tmi_File_EditFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Mode (parse Subfolders).
        /// </summary>
        public static string tmi_File_FlatMode {
            get {
                return ResourceManager.GetString("tmi_File_FlatMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export GPX/JSON Track Files.
        /// </summary>
        public static string tmi_File_ImportExportGPX {
            get {
                return ResourceManager.GetString("tmi_File_ImportExportGPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste All Geodata.
        /// </summary>
        public static string tmi_File_PasteGeoData {
            get {
                return ResourceManager.GetString("tmi_File_PasteGeoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string tmi_File_Quit {
            get {
                return ResourceManager.GetString("tmi_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string tmi_File_SaveAll {
            get {
                return ResourceManager.GetString("tmi_File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string tmi_Help {
            get {
                return ResourceManager.GetString("tmi_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tmi_Help_About {
            get {
                return ResourceManager.GetString("tmi_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a bug report (GitHub).
        /// </summary>
        public static string tmi_Help_BugReport {
            get {
                return ResourceManager.GetString("tmi_Help_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a feature request (GitHub).
        /// </summary>
        public static string tmi_Help_FeedbackFeatureRequest {
            get {
                return ResourceManager.GetString("tmi_Help_FeedbackFeatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tmi_Settings {
            get {
                return ResourceManager.GetString("tmi_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favourites.
        /// </summary>
        public static string tmi_Settings_Favourites {
            get {
                return ResourceManager.GetString("tmi_Settings_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tmi_Settings_Settings {
            get {
                return ResourceManager.GetString("tmi_Settings_Settings", resourceCulture);
            }
        }
    }
}
